package io.kestra.plugin.coda.automations;

import io.kestra.core.models.annotations.Example;
import io.kestra.core.models.annotations.Plugin;
import io.kestra.core.models.annotations.PluginProperty;
import io.kestra.core.models.property.Property;
import io.kestra.core.models.tasks.RunnableTask;
import io.kestra.core.models.tasks.Task;
import io.kestra.core.runners.RunContext;
import io.kestra.plugin.coda.exceptions.CodaAuthenticationException;
import io.kestra.plugin.coda.exceptions.CodaException;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Builder;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.ToString;
import lombok.experimental.SuperBuilder;
import okhttp3.*;
import org.slf4j.Logger;

import jakarta.validation.constraints.NotNull;
import java.io.IOException;
import java.util.Map;

/**
 * Trigger a Coda automation via webhook.
 *
 * This task sends a POST request to a Coda webhook URL to trigger an automation.
 * Webhooks in Coda allow you to execute automations from external applications.
 *
 * <h2>Setting Up a Webhook in Coda:</h2>
 * <ol>
 *   <li>Open your Coda document</li>
 *   <li>Click the three-dot menu (⋮) → "Doc settings"</li>
 *   <li>Navigate to "Automations" → "+ Add rule"</li>
 *   <li>For the <strong>When</strong> condition, select "Webhook invoked"</li>
 *   <li>Coda generates a unique webhook URL</li>
 *   <li>Define the <strong>Then</strong> actions (e.g., add row, update table, send notification)</li>
 * </ol>
 *
 * <h2>Accessing Webhook Data in Automations:</h2>
 * <p>In your Coda automation, the webhook payload is available as <strong>"Step 1 Result"</strong>.</p>
 * <ul>
 *   <li>Use <code>ParseJSON([Step 1 Result], "key")</code> to extract values</li>
 *   <li>Example: <code>ParseJSON([Step 1 Result], "name")</code> returns the value of the "name" field</li>
 * </ul>
 */
@SuperBuilder
@ToString
@EqualsAndHashCode
@Getter
@NoArgsConstructor
@Schema(
    title = "Trigger Webhook",
    description = "Trigger a Coda automation by sending a POST request to a webhook URL. " +
        "The webhook payload will be available in the automation as 'Step 1 Result'."
)
@Plugin(
    examples = {
        @Example(
            title = "Trigger a simple webhook with data",
            code = {
                "apiToken: \"{{ secret('CODA_API_TOKEN') }}\"",
                "webhookUrl: \"https://coda.io/apis/v1/webhooks/abc-123-def\"",
                "payload:",
                "  name: \"John Doe\"",
                "  status: \"Active\"",
                "  priority: \"High\""
            }
        ),
        @Example(
            title = "Trigger webhook with numeric and boolean values",
            code = {
                "apiToken: \"{{ secret('CODA_API_TOKEN') }}\"",
                "webhookUrl: \"https://coda.io/apis/v1/webhooks/abc-123-def\"",
                "payload:",
                "  taskName: \"Complete Documentation\"",
                "  daysRemaining: 5",
                "  isUrgent: true",
                "  assignee: \"team@example.com\""
            }
        ),
        @Example(
            title = "Trigger webhook with array data",
            code = {
                "apiToken: \"{{ secret('CODA_API_TOKEN') }}\"",
                "webhookUrl: \"https://coda.io/apis/v1/webhooks/abc-123-def\"",
                "payload:",
                "  eventType: \"batch_update\"",
                "  items:",
                "    - name: \"Alice\"",
                "      score: 95",
                "    - name: \"Bob\"",
                "      score: 87"
            }
        ),
        @Example(
            title = "Trigger webhook with nested data",
            code = {
                "apiToken: \"{{ secret('CODA_API_TOKEN') }}\"",
                "webhookUrl: \"https://coda.io/apis/v1/webhooks/abc-123-def\"",
                "payload:",
                "  order:",
                "    id: \"ORD-12345\"",
                "    customer:",
                "      name: \"John Doe\"",
                "      email: \"john@example.com\"",
                "    total: 99.99",
                "    status: \"pending\""
            }
        )
    }
)
public class TriggerWebhook extends Task implements RunnableTask<TriggerWebhook.Output> {

    @Schema(
        title = "Coda API Token",
        description = "Your Coda API token. Get it from https://coda.io/account. " +
            "We recommend using Kestra secrets to store this value securely."
    )
    @NotNull
    @PluginProperty(dynamic = true)
    protected Property<String> apiToken;

    @Schema(
        title = "Webhook URL",
        description = "The webhook URL generated by Coda when you create a webhook-triggered automation. " +
            "Format: https://coda.io/apis/v1/webhooks/{webhookId}"
    )
    @NotNull
    @PluginProperty(dynamic = true)
    protected Property<String> webhookUrl;

    @Schema(
        title = "Payload",
        description = "The JSON payload to send to the webhook. " +
            "This data will be available in your Coda automation as 'Step 1 Result'. " +
            "Use ParseJSON([Step 1 Result], \"key\") in Coda formulas to extract values."
    )
    @NotNull
    @PluginProperty(dynamic = true)
    protected Property<Map<String, Object>> payload;

    @Schema(
        title = "Connection Timeout",
        description = "Connection timeout in seconds. Default is 30 seconds.",
        defaultValue = "30"
    )
    @PluginProperty
    @Builder.Default
    protected Property<Integer> connectionTimeout = Property.of(30);

    @Schema(
        title = "Read Timeout",
        description = "Read timeout in seconds. Default is 30 seconds.",
        defaultValue = "30"
    )
    @PluginProperty
    @Builder.Default
    protected Property<Integer> readTimeout = Property.of(30);

    @Override
    public Output run(RunContext runContext) throws Exception {
        Logger logger = runContext.logger();

        // Render properties
        String renderedApiToken = runContext.render(apiToken).as(String.class).orElseThrow();
        String renderedWebhookUrl = runContext.render(webhookUrl).as(String.class).orElseThrow();
        Map<String, Object> renderedPayload = runContext.render(payload).asMap(String.class, Object.class);
        int connTimeout = runContext.render(connectionTimeout).as(Integer.class).orElse(30);
        int rdTimeout = runContext.render(readTimeout).as(Integer.class).orElse(30);

        logger.info("Triggering Coda webhook: {}", renderedWebhookUrl);
        logger.debug("Payload: {}", renderedPayload);

        // Build HTTP client
        OkHttpClient client = new OkHttpClient.Builder()
            .connectTimeout(connTimeout, java.util.concurrent.TimeUnit.SECONDS)
            .readTimeout(rdTimeout, java.util.concurrent.TimeUnit.SECONDS)
            .build();

        // Convert payload to JSON
        String jsonPayload = new com.google.gson.Gson().toJson(renderedPayload);

        // Build request
        RequestBody body = RequestBody.create(
            jsonPayload,
            MediaType.get("application/json; charset=utf-8")
        );

        Request request = new Request.Builder()
            .url(renderedWebhookUrl)
            .post(body)
            .addHeader("Authorization", "Bearer " + renderedApiToken)
            .addHeader("Content-Type", "application/json")
            .build();

        // Execute request
        try (Response response = client.newCall(request).execute()) {
            int statusCode = response.code();
            String responseBody = response.body() != null ? response.body().string() : "";

            logger.debug("Response status code: {}", statusCode);
            logger.debug("Response body: {}", responseBody);

            if (statusCode == 401 || statusCode == 403) {
                throw new CodaAuthenticationException(
                    "Authentication failed. Please check your API token. Status: " + statusCode
                );
            }

            if (!response.isSuccessful()) {
                throw new CodaException(
                    "Failed to trigger webhook. Status: " + statusCode + ", Response: " + responseBody
                );
            }

            logger.info("Webhook triggered successfully. Status code: {}", statusCode);

            return Output.builder()
                .statusCode(statusCode)
                .responseBody(responseBody)
                .webhookUrl(renderedWebhookUrl)
                .success(true)
                .build();

        } catch (IOException e) {
            logger.error("Failed to trigger webhook", e);
            throw new CodaException("Failed to trigger webhook: " + e.getMessage(), e);
        }
    }

    @Builder
    @Getter
    public static class Output implements io.kestra.core.models.tasks.Output {
        @Schema(
            title = "Success",
            description = "Whether the webhook was triggered successfully"
        )
        private final boolean success;

        @Schema(
            title = "Status Code",
            description = "HTTP status code returned by the webhook endpoint"
        )
        private final int statusCode;

        @Schema(
            title = "Response Body",
            description = "Response body returned by the webhook endpoint"
        )
        private final String responseBody;

        @Schema(
            title = "Webhook URL",
            description = "The webhook URL that was triggered"
        )
        private final String webhookUrl;
    }
}
